#!/usr/bin/env bash
# This file will create a script to install and
# configure HAProxy on lb-01 server

sudo apt-get -y update
apt-get -y install haproxy

# edit config file
server_config=\
"
frontend  wem-frontend
        bind *:80
        mode http
        default_backend leo-backend
backend wem-backend
        balance roundrobin
        server 63210-web-01 54.162.0.146:80 check
        server 63210-web-02 54.84.180.249:80 check
"
echo "$server_config" | sudo tee -a /etc/haproxy/haproxy.cfg

echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

sudo service haproxy restart
