#!/usr/bin/env bash
# Implementing the SIGTERM signal when a kill is called
# I am invincible!!! will be displayed
trap 'echo "I am invincible!!!"' SIGTERM
while true
do
	echo "To infinity and beyond"
	sleep 2
done
