#!/usr/bin/env bash
# This script prints 1 - 20 
# using case statement for conditions
# in between the loop

a=1
while [ $a -le 20 ]
do
	case $a in
		"4") echo "bad luck for China";;
		"9") echo "bad luck for Japan";;
		"17") echo "bad luck for Italy";;
	esac
	a=$((a+1))
done
