#!/usr/bin/env bash
# This script will display the time and the hour
# 12 hours and 59 minutes

H=0
while [ $H -le 12 ]
do
	echo "Hour: $H"
	M=1
	while [ $M -lt 60 ]
	do
		echo $M
		M=$((M+1))
	done
	H=$((H+1))
done
