#!/usr/bin/env bash
# This wil configure a ufw firewall to block all incoming traffic
# but will not change or affect TCP ports 22, 443 and 80.

apt-get install ufw
sed -i 's/IPV6=.*/IPV6=yes/' /etc/default/ufw
ufw disable
ufw enable
ufw default deny incoming
ufw default allow outgoing
ufw allow 22/tcp
ufw allow 443/tcp
ufw allow 80/tcp
